"""correcao da chave title da tabela cardModel

Revision ID: 5c9858cc9901
Revises: 77c3e4730664
Create Date: 2022-03-04 12:43:30.466224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9858cc9901'
down_revision = '77c3e4730664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('title', sa.String(length=64), nullable=False))
    op.drop_column('cards', 'tile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('tile', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('cards', 'title')
    # ### end Alembic commands ###
